### ISSUE TITLE
use the email validator instead of the regex

### ISSUE THREAD

**Issue by lordadamson** [Ketabuk/Ketabuk-Webfront#120]
depends on #119

**Comment by Kadaaran** [comment]
Hey there, I think I can help. Can you provide more informations ?
About the email validator, is it form authentication ?

**Comment by lordadamson** [comment]
Hi @Kadaaran and welcome! :D
Yes it was supposed to be for form authentication. I kind of forgot that I need to remove the email from the registration process because this website needs so much privacy for its members.
I'll have to close this issue now but please feel free to look around the project for other issues that might interest you :D Have a nice day.
